//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoServicio.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.serviciosSoap")]
    public interface serviciosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saludar(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> saludarAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sumar(int numero01, int numero02);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sumarAsync(int numero01, int numero02);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aumentar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string aumentar(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aumentar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> aumentarAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviciosSoapChannel : ConsumoServicio.ServiceReference1.serviciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviciosSoapClient : System.ServiceModel.ClientBase<ConsumoServicio.ServiceReference1.serviciosSoap>, ConsumoServicio.ServiceReference1.serviciosSoap {
        
        public serviciosSoapClient() {
        }
        
        public serviciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string saludar(string nombre) {
            return base.Channel.saludar(nombre);
        }
        
        public System.Threading.Tasks.Task<string> saludarAsync(string nombre) {
            return base.Channel.saludarAsync(nombre);
        }
        
        public string sumar(int numero01, int numero02) {
            return base.Channel.sumar(numero01, numero02);
        }
        
        public System.Threading.Tasks.Task<string> sumarAsync(int numero01, int numero02) {
            return base.Channel.sumarAsync(numero01, numero02);
        }
        
        public string aumentar(int numero) {
            return base.Channel.aumentar(numero);
        }
        
        public System.Threading.Tasks.Task<string> aumentarAsync(int numero) {
            return base.Channel.aumentarAsync(numero);
        }
    }
}
