//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoServicio.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.serviciosSoap")]
    public interface serviciosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saludar(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saludar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> saludarAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sumar(int numero01, int numero02);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sumarAsync(int numero01, int numero02);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aumentar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string aumentar(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aumentar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> aumentarAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GuardarLog(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GuardarLogAsync(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar3N", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Sumar3N(int num_01, int num_02, int num_03);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar3N", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Sumar3NAsync(int num_01, int num_02, int num_03);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerFrutas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ObtenerFrutas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerFrutas", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ObtenerFrutasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarFrutas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GuardarFrutas(string[] frutas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarFrutas", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GuardarFrutasAsync(string[] frutas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEquipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsumoServicio.ServiceReference2.Equipos[] ObtenerEquipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEquipos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.Equipos[]> ObtenerEquiposAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Equipos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviciosSoapChannel : ConsumoServicio.ServiceReference2.serviciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviciosSoapClient : System.ServiceModel.ClientBase<ConsumoServicio.ServiceReference2.serviciosSoap>, ConsumoServicio.ServiceReference2.serviciosSoap {
        
        public serviciosSoapClient() {
        }
        
        public serviciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string saludar(string nombre) {
            return base.Channel.saludar(nombre);
        }
        
        public System.Threading.Tasks.Task<string> saludarAsync(string nombre) {
            return base.Channel.saludarAsync(nombre);
        }
        
        public string sumar(int numero01, int numero02) {
            return base.Channel.sumar(numero01, numero02);
        }
        
        public System.Threading.Tasks.Task<string> sumarAsync(int numero01, int numero02) {
            return base.Channel.sumarAsync(numero01, numero02);
        }
        
        public string aumentar(int numero) {
            return base.Channel.aumentar(numero);
        }
        
        public System.Threading.Tasks.Task<string> aumentarAsync(int numero) {
            return base.Channel.aumentarAsync(numero);
        }
        
        public string GuardarLog(string mensaje) {
            return base.Channel.GuardarLog(mensaje);
        }
        
        public System.Threading.Tasks.Task<string> GuardarLogAsync(string mensaje) {
            return base.Channel.GuardarLogAsync(mensaje);
        }
        
        public int Sumar3N(int num_01, int num_02, int num_03) {
            return base.Channel.Sumar3N(num_01, num_02, num_03);
        }
        
        public System.Threading.Tasks.Task<int> Sumar3NAsync(int num_01, int num_02, int num_03) {
            return base.Channel.Sumar3NAsync(num_01, num_02, num_03);
        }
        
        public string[] ObtenerFrutas() {
            return base.Channel.ObtenerFrutas();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerFrutasAsync() {
            return base.Channel.ObtenerFrutasAsync();
        }
        
        public string GuardarFrutas(string[] frutas) {
            return base.Channel.GuardarFrutas(frutas);
        }
        
        public System.Threading.Tasks.Task<string> GuardarFrutasAsync(string[] frutas) {
            return base.Channel.GuardarFrutasAsync(frutas);
        }
        
        public ConsumoServicio.ServiceReference2.Equipos[] ObtenerEquipos() {
            return base.Channel.ObtenerEquipos();
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.Equipos[]> ObtenerEquiposAsync() {
            return base.Channel.ObtenerEquiposAsync();
        }
    }
}
